openapi: 3.0.0
info:
    title: Sample API
    description: Optional
    version: 0.1.9
servers:
    - url: http://localhost:3000/api/v1
      description: Optional server description, e.g. Main (production) server
paths:
    /users:
        get:
            tags:
                - Users
            summary: Returns a list of users.
            description: Optional
            responses:
                '200': # status code
                    description: List of users
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
    /products:
        get:
            tags:
                - Products
            summary: Returns a list of products.
            description: Optional
            responses:
                '200': # status code
                    description: List of products
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
